# Generated by Django 4.0.1 on 2022-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
